FROM ruby:2.7.5

WORKDIR /backend
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN apt-get install -y cron

COPY Gemfile* .
RUN bundle install
COPY . .

EXPOSE 3000

CMD ["./docker-entrypoint.sh"]
